// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/aandriat/CMSSW_7_6_3_patch2/src/test_13TeV/GenAcceptance/./../Utils/CPlot.hh;
#pragma link C++ defined_in "/home/aandriat/CMSSW_7_6_3_patch2/src/test_13TeV/GenAcceptance/./../Utils/CPlot.cc";

#endif
